[package]
name = "mosquitto-identity-plugin"
version = "0.1.0"
edition = "2021"

[lib]
crate-type=["dylib"]

[dependencies]
libc = "0.2.133"

[build-dependencies]
bindgen = { version = "0.60.1", default-features = false, features = ["runtime"] }